### ISSUE TITLE
UndertowWebContext getRequestParameters crashes

### ISSUE THREAD

**Issue by rikardev** [pac4j/undertow-pac4j#116]
https://github.com/pac4j/undertow-pac4j/blob/fb2226d97b5d81943734498be0193dc9fd817fce/src/main/java/org/pac4j/undertow/context/UndertowWebContext.java#L61

This line throws an exception for me:

```
java.lang.ArrayStoreException: arraycopy: element type mismatch: can not cast one of the elements of java.lang.Object[] to the type of the destination array, java.lang.String
```

This happens when trying to get the request parameters from the callback post in the open id connect code flow. It's trying to get the "code" parameter.

So trying to cast a `FormValueImpl` to a String doesn't work?

Running the latest release versions and tried with both java 11 and java 17 both with the same error.

**Comment by leleuj** [comment]
I use the demo: https://github.com/pac4j/undertow-pac4j-demo

I'm not able to reproduce the problem with an OIDC login process. Can you elaborate? Thanks

**Comment by rikardev** [comment]
Thanks for the reply.
Yes that works for me too and it works when I use the OidcClient config from that project in my code but doesn't work with my config. One thing I had to alter to try your config in my code was to expose it via http instead of what I do https. It didn't allow me to configure an https callback from your config so couldn't try that. Could be a clue maybe?

**Comment by leleuj** [comment]
Using HTTP or HTTPS shouldn't make any difference.
Can you privately share a small demo demonstrating your problem (jerome@casinthecloud.com)?

**Comment by rikardev** [comment]
If I add the following two lines of configuration to the undertow-pac4j-demo I can reproduce the error running that:
```
oidcConfiguration.setResponseType("code");
oidcConfiguration.setResponseMode("form_post");
```
here:
https://github.com/pac4j/undertow-pac4j-demo/blob/master/src/main/java/org/pac4j/demo/undertow/DemoConfigFactory.java#L34

**Comment by leleuj** [comment]
Good! Indeed, there is a bug. Can you try v5.0.1-SNAPSHOT and report? Thanks

**Comment by rikardev** [comment]
Tried it and it works, thanks!

**Comment by leleuj** [comment]
Excellent! I will release a version 5.0.1.
