### ISSUE TITLE
Upgrade to pac4j v2.2.1

### ISSUE THREAD

**Issue by zimmi** [pac4j/undertow-pac4j#27]
I'm using undertow-pac4j v1.2.3 with pac4j-oidc v2.2.1, like this:

```xml
<dependency>
    <groupId>org.pac4j</groupId>
    <artifactId>undertow-pac4j</artifactId>
    <version>1.2.3</version>
    <exclusions>
        <!-- Rely on transitive dependency of pac4j-oidc (undertow-pac4j is a bit behind) -->
        <exclusion>
            <groupId>org.pac4j</groupId>
            <artifactId>pac4j-core</artifactId>
        </exclusion>
    </exclusions>
</dependency>
            
<dependency>
    <groupId>org.pac4j</groupId>
    <artifactId>pac4j-oidc</artifactId>
    <version>2.2.1</version>
</dependency>
```

Right now this gets me:

```
java.lang.NoClassDefFoundError: org/pac4j/core/engine/ApplicationLogoutLogic
	at com.mycompany.webapi.TraceDisabledTest.setup(TraceDisabledTest.java:24)
Caused by: java.lang.ClassNotFoundException: org.pac4j.core.engine.ApplicationLogoutLogic
	at com.mycompany.webapi.TraceDisabledTest.setup(TraceDisabledTest.java:24)
```

I'll try with pac4j v1.9.9, but it would still be nice to be on a somewhat recent version.
Anyway, thanks a ton for pac4j, after reading the docs and demo app it's pretty straightforward to integrate!

Edit: This seems to be the same problem as reported [on the mailing list](https://groups.google.com/d/topic/pac4j-users/BAxhvFpN4Uo/discussion).

**Comment by leleuj** [comment]
Indeed, undertow-pac4j has not been upgraded to pac4j v2.x. I plan to do the upgrade after the release of pac4j v3.

**Comment by zimmi** [comment]
Woops, should have read this earlier. Well, there is now an intermediate PR for 2.2.1: #28

**Comment by leleuj** [comment]
Upgrading libraries always take a lot of time because there are 15 pac4j implementations. So we can upgrade to pac4j right now, it will be less work for the version 3.0.0 then.
