### ISSUE TITLE
Not available via Maven Central

### ISSUE THREAD

**Issue by kjellski** [pac4j/undertow-pac4j#3]
Is there anything hindering this project from beeing released on maven central? I'd love to be able to just install it via maven.

Also, I was unable to find it on Sonatype, any hints?

**Comment by leleuj** [comment]
Promoting / presenting libraries takes a lot of time and we didn't find some for Undertow yet. But I'm glad to have a first feedback.

I could cut a release pretty quickly.

I set up a build on Travis for `undertow-pac4j`, it should be available in Sonatype repositories in a few minutes.

**Comment by kjellski** [comment]
That sounds very good! :) Thanks a lot!

**Comment by kjellski** [comment]
Got my hands on removing my submodule and added the dependency as per README.md.

It's working, confirmed! Thanks a lot!
