### ISSUE TITLE
Change roles in db, but not reflected in undertow pac4j ?

### ISSUE THREAD

**Issue by albert-kam** [pac4j/undertow-pac4j#35]
Hi, using pac4j 3.8.3, undertow-pac4j 3.0.0, and undertow-servlet 2.1.0.Final.

Here's my flow leading to the unexpected:

1. So i login using a user with roles of 'admin,developer', and the menu available for developer is visible in my rendered html.
2. Then i remove the developer role using `update t_user set roles = 'admin' where id = 'anana';`
3. And i tried browser refresh, and the menu for developer is still visible.
4. I tried relogin, hoping to clear the caching somewhere, but the menu is still there.
5. I had to restart undertow and login with that user, and finally the menu for developer is now not rendered.

In my case, i always get the User instance using getActor(HttpServerExchange exchange), there are no caching from my application code:

```
public User getActor(HttpServerExchange exchange) {
	SecurityContext securityContext = exchange.getSecurityContext();
	if (securityContext != null) {
		Account account = securityContext.getAuthenticatedAccount();
		if (account instanceof Pac4jAccount) {
			List<CommonProfile> profiles= ((Pac4jAccount) account).getProfiles();
			CommonProfile profile = profiles.get(0);
			Map<String, Object> attributes = profile.getAttributes();
			return User.builder()
				.withId(profile.getId())
				.withEmail((String) attributes.get("email"))
				.withRoles((String) attributes.get("roles"))
				.withName(profile.getDisplayName())
				.build();
		}
	} else {
		System.out.println("null security context !");
	}
	return null;
}
```

Any pointers to have the User instance to reflect the live database without having to restarting the server ?
Thank you ..

**Comment by leleuj** [comment]
Hi,

Please use the mailing list for questions: https://groups.google.com/g/pac4j-users
