### ISSUE TITLE
Use attachments to store request attributes

### ISSUE THREAD

**Issue by igor-b180** [pac4j/undertow-pac4j#50]
As of version 4.0.0 `UndertowWebContext` uses Undertow's `HttpServerExchange.addPathParam(...)` to store request attributes. Since path parameters are strings, undertow-pac4j uses Java serialization and base64 encoding to convert any object to a string. This is problematic for us, because we use non-serializable objects in our `UserProfile` object.

Is there a particular reason why string path parameters have to be used? Instead, `HttpServerExchange` has support for attachments, which could contain any objects, not just strings. This would also remove the overhead of serialization.

We have been able to work around it by extending `UndertowWebContext` and overriding the methods responsible for request parameters to use attachments instead, and it works for us. Happy to contribute via a pull request if this is of use.

**Comment by leleuj** [comment]
The main reason is that I'm no Undertow specialist ;-)

You're right, we can greatly improve that part. Please submit a PR with your proposed change.

**Comment by igor-b180** [comment]
Added a PR for the fix. Hope this could go into the next release, and we can remove our own workaround.
